export { WebGLArrayRenderTarget } from './renderers/WebGLArrayRenderTarget.js';
export { WebGL3DRenderTarget } from './renderers/WebGL3DRenderTarget.js';
export { WebGLCubeRenderTarget } from './renderers/WebGLCubeRenderTarget.js';
export { WebGLRenderTarget } from './renderers/WebGLRenderTarget.js';
export { WebGLRenderer } from './renderers/WebGLRenderer.js';
export { ShaderLib } from './renderers/shaders/ShaderLib.js';
export { UniformsLib } from './renderers/shaders/UniformsLib.js';
export { UniformsUtils } from './renderers/shaders/UniformsUtils.js';
export { ShaderChunk } from './renderers/shaders/ShaderChunk.js';
export { FogExp2 } from './scenes/FogExp2.js';
export { Fog } from './scenes/Fog.js';
export { Scene } from './scenes/Scene.js';
export { Sprite } from './objects/Sprite.js';
export { LOD } from './objects/LOD.js';
export { SkinnedMesh } from './objects/SkinnedMesh.js';
export { Skeleton } from './objects/Skeleton.js';
export { Bone } from './objects/Bone.js';
export { Mesh } from './objects/Mesh.js';
export { InstancedMesh } from './objects/InstancedMesh.js';
export { BatchedMesh } from './objects/BatchedMesh.js';
export { LineSegments } from './objects/LineSegments.js';
export { LineLoop } from './objects/LineLoop.js';
export { Line } from './objects/Line.js';
export { Points } from './objects/Points.js';
export { Group } from './objects/Group.js';
export { VideoTexture } from './textures/VideoTexture.js';
export { FramebufferTexture } from './textures/FramebufferTexture.js';
export { Source } from './textures/Source.js';
export { DataTexture } from './textures/DataTexture.js';
export { DataArrayTexture } from './textures/DataArrayTexture.js';
export { Data3DTexture } from './textures/Data3DTexture.js';
export { CompressedTexture } from './textures/CompressedTexture.js';
export { CompressedArrayTexture } from './textures/CompressedArrayTexture.js';
export { CompressedCubeTexture } from './textures/CompressedCubeTexture.js';
export { CubeTexture } from './textures/CubeTexture.js';
export { CanvasTexture } from './textures/CanvasTexture.js';
export { DepthTexture } from './textures/DepthTexture.js';
export { Texture } from './textures/Texture.js';
export { AnimationLoader } from './loaders/AnimationLoader.js';
export { CompressedTextureLoader } from './loaders/CompressedTextureLoader.js';
export { CubeTextureLoader } from './loaders/CubeTextureLoader.js';
export { DataTextureLoader } from './loaders/DataTextureLoader.js';
export { TextureLoader } from './loaders/TextureLoader.js';
export { ObjectLoader } from './loaders/ObjectLoader.js';
export { MaterialLoader } from './loaders/MaterialLoader.js';
export { BufferGeometryLoader } from './loaders/BufferGeometryLoader.js';
export { DefaultLoadingManager, LoadingManager } from './loaders/LoadingManager.js';
export { ImageLoader } from './loaders/ImageLoader.js';
export { ImageBitmapLoader } from './loaders/ImageBitmapLoader.js';
export { FileLoader } from './loaders/FileLoader.js';
export { Loader } from './loaders/Loader.js';
export { LoaderUtils } from './loaders/LoaderUtils.js';
export { Cache } from './loaders/Cache.js';
export { AudioLoader } from './loaders/AudioLoader.js';
export { SpotLight } from './lights/SpotLight.js';
export { PointLight } from './lights/PointLight.js';
export { RectAreaLight } from './lights/RectAreaLight.js';
export { HemisphereLight } from './lights/HemisphereLight.js';
export { DirectionalLight } from './lights/DirectionalLight.js';
export { AmbientLight } from './lights/AmbientLight.js';
export { Light } from './lights/Light.js';
export { LightProbe } from './lights/LightProbe.js';
export { StereoCamera } from './cameras/StereoCamera.js';
export { PerspectiveCamera } from './cameras/PerspectiveCamera.js';
export { OrthographicCamera } from './cameras/OrthographicCamera.js';
export { CubeCamera } from './cameras/CubeCamera.js';
export { ArrayCamera } from './cameras/ArrayCamera.js';
export { Camera } from './cameras/Camera.js';
export { AudioListener } from './audio/AudioListener.js';
export { PositionalAudio } from './audio/PositionalAudio.js';
export { AudioContext } from './audio/AudioContext.js';
export { AudioAnalyser } from './audio/AudioAnalyser.js';
export { Audio } from './audio/Audio.js';
export { VectorKeyframeTrack } from './animation/tracks/VectorKeyframeTrack.js';
export { StringKeyframeTrack } from './animation/tracks/StringKeyframeTrack.js';
export { QuaternionKeyframeTrack } from './animation/tracks/QuaternionKeyframeTrack.js';
export { NumberKeyframeTrack } from './animation/tracks/NumberKeyframeTrack.js';
export { ColorKeyframeTrack } from './animation/tracks/ColorKeyframeTrack.js';
export { BooleanKeyframeTrack } from './animation/tracks/BooleanKeyframeTrack.js';
export { PropertyMixer } from './animation/PropertyMixer.js';
export { PropertyBinding } from './animation/PropertyBinding.js';
export { KeyframeTrack } from './animation/KeyframeTrack.js';
export { AnimationUtils } from './animation/AnimationUtils.js';
export { AnimationObjectGroup } from './animation/AnimationObjectGroup.js';
export { AnimationMixer } from './animation/AnimationMixer.js';
export { AnimationClip } from './animation/AnimationClip.js';
export { AnimationAction } from './animation/AnimationAction.js';
export { RenderTarget } from './core/RenderTarget.js';
export { Uniform } from './core/Uniform.js';
export { UniformsGroup } from './core/UniformsGroup.js';
export { InstancedBufferGeometry } from './core/InstancedBufferGeometry.js';
export { BufferGeometry } from './core/BufferGeometry.js';
export { InterleavedBufferAttribute } from './core/InterleavedBufferAttribute.js';
export { InstancedInterleavedBuffer } from './core/InstancedInterleavedBuffer.js';
export { InterleavedBuffer } from './core/InterleavedBuffer.js';
export { InstancedBufferAttribute } from './core/InstancedBufferAttribute.js';
export { GLBufferAttribute } from './core/GLBufferAttribute.js';
export { Object3D } from './core/Object3D.js';
export { Raycaster } from './core/Raycaster.js';
export { Layers } from './core/Layers.js';
export { EventDispatcher } from './core/EventDispatcher.js';
export { Clock } from './core/Clock.js';
export { QuaternionLinearInterpolant } from './math/interpolants/QuaternionLinearInterpolant.js';
export { LinearInterpolant } from './math/interpolants/LinearInterpolant.js';
export { DiscreteInterpolant } from './math/interpolants/DiscreteInterpolant.js';
export { CubicInterpolant } from './math/interpolants/CubicInterpolant.js';
export { Interpolant } from './math/Interpolant.js';
export { Triangle } from './math/Triangle.js';
export { MathUtils } from './math/MathUtils.js';
export { Spherical } from './math/Spherical.js';
export { Cylindrical } from './math/Cylindrical.js';
export { Plane } from './math/Plane.js';
export { Frustum } from './math/Frustum.js';
export { Sphere } from './math/Sphere.js';
export { Ray } from './math/Ray.js';
export { Matrix4 } from './math/Matrix4.js';
export { Matrix3 } from './math/Matrix3.js';
export { Box3 } from './math/Box3.js';
export { Box2 } from './math/Box2.js';
export { Line3 } from './math/Line3.js';
export { Euler } from './math/Euler.js';
export { Vector4 } from './math/Vector4.js';
export { Vector3 } from './math/Vector3.js';
export { Vector2 } from './math/Vector2.js';
export { Quaternion } from './math/Quaternion.js';
export { Color } from './math/Color.js';
export { ColorManagement } from './math/ColorManagement.js';
export { SphericalHarmonics3 } from './math/SphericalHarmonics3.js';
export { SpotLightHelper } from './helpers/SpotLightHelper.js';
export { SkeletonHelper } from './helpers/SkeletonHelper.js';
export { PointLightHelper } from './helpers/PointLightHelper.js';
export { HemisphereLightHelper } from './helpers/HemisphereLightHelper.js';
export { GridHelper } from './helpers/GridHelper.js';
export { PolarGridHelper } from './helpers/PolarGridHelper.js';
export { DirectionalLightHelper } from './helpers/DirectionalLightHelper.js';
export { CameraHelper } from './helpers/CameraHelper.js';
export { BoxHelper } from './helpers/BoxHelper.js';
export { Box3Helper } from './helpers/Box3Helper.js';
export { PlaneHelper } from './helpers/PlaneHelper.js';
export { ArrowHelper } from './helpers/ArrowHelper.js';
export { AxesHelper } from './helpers/AxesHelper.js';
export { Shape } from './extras/core/Shape.js';
export { Path } from './extras/core/Path.js';
export { ShapePath } from './extras/core/ShapePath.js';
export { CurvePath } from './extras/core/CurvePath.js';
export { Curve } from './extras/core/Curve.js';
export { DataUtils } from './extras/DataUtils.js';
export { ImageUtils } from './extras/ImageUtils.js';
export { ShapeUtils } from './extras/ShapeUtils.js';
export { TextureUtils } from './extras/TextureUtils.js';
export { PMREMGenerator } from './extras/PMREMGenerator.js';
export { WebGLUtils } from './renderers/webgl/WebGLUtils.js';
export { createCanvasElement } from './utils.js';
export { BoxGeometry } from './geometries/BoxGeometry.js';
export { CapsuleGeometry } from './geometries/CapsuleGeometry.js';
export { CircleGeometry } from './geometries/CircleGeometry.js';
export { ConeGeometry } from './geometries/ConeGeometry.js';
export { CylinderGeometry } from './geometries/CylinderGeometry.js';
export { DodecahedronGeometry } from './geometries/DodecahedronGeometry.js';
export { EdgesGeometry } from './geometries/EdgesGeometry.js';
export { ExtrudeGeometry } from './geometries/ExtrudeGeometry.js';
export { IcosahedronGeometry } from './geometries/IcosahedronGeometry.js';
export { LatheGeometry } from './geometries/LatheGeometry.js';
export { OctahedronGeometry } from './geometries/OctahedronGeometry.js';
export { PlaneGeometry } from './geometries/PlaneGeometry.js';
export { PolyhedronGeometry } from './geometries/PolyhedronGeometry.js';
export { RingGeometry } from './geometries/RingGeometry.js';
export { ShapeGeometry } from './geometries/ShapeGeometry.js';
export { SphereGeometry } from './geometries/SphereGeometry.js';
export { TetrahedronGeometry } from './geometries/TetrahedronGeometry.js';
export { TorusGeometry } from './geometries/TorusGeometry.js';
export { TorusKnotGeometry } from './geometries/TorusKnotGeometry.js';
export { TubeGeometry } from './geometries/TubeGeometry.js';
export { WireframeGeometry } from './geometries/WireframeGeometry.js';
export { ShadowMaterial } from './materials/ShadowMaterial.js';
export { SpriteMaterial } from './materials/SpriteMaterial.js';
export { RawShaderMaterial } from './materials/RawShaderMaterial.js';
export { ShaderMaterial } from './materials/ShaderMaterial.js';
export { PointsMaterial } from './materials/PointsMaterial.js';
export { MeshPhysicalMaterial } from './materials/MeshPhysicalMaterial.js';
export { MeshStandardMaterial } from './materials/MeshStandardMaterial.js';
export { MeshPhongMaterial } from './materials/MeshPhongMaterial.js';
export { MeshToonMaterial } from './materials/MeshToonMaterial.js';
export { MeshNormalMaterial } from './materials/MeshNormalMaterial.js';
export { MeshLambertMaterial } from './materials/MeshLambertMaterial.js';
export { MeshDepthMaterial } from './materials/MeshDepthMaterial.js';
export { MeshDistanceMaterial } from './materials/MeshDistanceMaterial.js';
export { MeshBasicMaterial } from './materials/MeshBasicMaterial.js';
export { MeshMatcapMaterial } from './materials/MeshMatcapMaterial.js';
export { LineDashedMaterial } from './materials/LineDashedMaterial.js';
export { LineBasicMaterial } from './materials/LineBasicMaterial.js';
export { Material } from './materials/Material.js';
export { BufferAttribute, Float16BufferAttribute, Float32BufferAttribute, Int16BufferAttribute, Int32BufferAttribute, Int8BufferAttribute, Uint16BufferAttribute, Uint32BufferAttribute, Uint8BufferAttribute, Uint8ClampedBufferAttribute } from './core/BufferAttribute.js';
export { ArcCurve } from './extras/curves/ArcCurve.js';
export { CatmullRomCurve3 } from './extras/curves/CatmullRomCurve3.js';
export { CubicBezierCurve } from './extras/curves/CubicBezierCurve.js';
export { CubicBezierCurve3 } from './extras/curves/CubicBezierCurve3.js';
export { EllipseCurve } from './extras/curves/EllipseCurve.js';
export { LineCurve } from './extras/curves/LineCurve.js';
export { LineCurve3 } from './extras/curves/LineCurve3.js';
export { QuadraticBezierCurve } from './extras/curves/QuadraticBezierCurve.js';
export { QuadraticBezierCurve3 } from './extras/curves/QuadraticBezierCurve3.js';
export { SplineCurve } from './extras/curves/SplineCurve.js';
export { ACESFilmicToneMapping, AddEquation, AddOperation, AdditiveAnimationBlendMode, AdditiveBlending, AgXToneMapping, AlphaFormat, AlwaysCompare, AlwaysDepth, AlwaysStencilFunc, AttachedBindMode, BackSide, BasicDepthPacking, BasicShadowMap, ByteType, CineonToneMapping, ClampToEdgeWrapping, ConstantAlphaFactor, ConstantColorFactor, CubeReflectionMapping, CubeRefractionMapping, CubeUVReflectionMapping, CullFaceBack, CullFaceFront, CullFaceFrontBack, CullFaceNone, CustomBlending, CustomToneMapping, DecrementStencilOp, DecrementWrapStencilOp, DepthFormat, DepthStencilFormat, DetachedBindMode, DisplayP3ColorSpace, DoubleSide, DstAlphaFactor, DstColorFactor, DynamicCopyUsage, DynamicDrawUsage, DynamicReadUsage, EqualCompare, EqualDepth, EqualStencilFunc, EquirectangularReflectionMapping, EquirectangularRefractionMapping, FloatType, FrontSide, GLSL1, GLSL3, GreaterCompare, GreaterDepth, GreaterEqualCompare, GreaterEqualDepth, GreaterEqualStencilFunc, GreaterStencilFunc, HalfFloatType, IncrementStencilOp, IncrementWrapStencilOp, IntType, InterpolateDiscrete, InterpolateLinear, InterpolateSmooth, InvertStencilOp, KeepStencilOp, LessCompare, LessDepth, LessEqualCompare, LessEqualDepth, LessEqualStencilFunc, LessStencilFunc, LinearDisplayP3ColorSpace, LinearFilter, LinearMipMapLinearFilter, LinearMipMapNearestFilter, LinearMipmapLinearFilter, LinearMipmapNearestFilter, LinearSRGBColorSpace, LinearToneMapping, LinearTransfer, LoopOnce, LoopPingPong, LoopRepeat, LuminanceAlphaFormat, LuminanceFormat, MOUSE, MaxEquation, MinEquation, MirroredRepeatWrapping, MixOperation, MultiplyBlending, MultiplyOperation, NearestFilter, NearestMipMapLinearFilter, NearestMipMapNearestFilter, NearestMipmapLinearFilter, NearestMipmapNearestFilter, NeutralToneMapping, NeverCompare, NeverDepth, NeverStencilFunc, NoBlending, NoColorSpace, NoToneMapping, NormalAnimationBlendMode, NormalBlending, NotEqualCompare, NotEqualDepth, NotEqualStencilFunc, ObjectSpaceNormalMap, OneFactor, OneMinusConstantAlphaFactor, OneMinusConstantColorFactor, OneMinusDstAlphaFactor, OneMinusDstColorFactor, OneMinusSrcAlphaFactor, OneMinusSrcColorFactor, P3Primaries, PCFShadowMap, PCFSoftShadowMap, RED_GREEN_RGTC2_Format, RED_RGTC1_Format, REVISION, RGBADepthPacking, RGBAFormat, RGBAIntegerFormat, RGBA_ASTC_10x10_Format, RGBA_ASTC_10x5_Format, RGBA_ASTC_10x6_Format, RGBA_ASTC_10x8_Format, RGBA_ASTC_12x10_Format, RGBA_ASTC_12x12_Format, RGBA_ASTC_4x4_Format, RGBA_ASTC_5x4_Format, RGBA_ASTC_5x5_Format, RGBA_ASTC_6x5_Format, RGBA_ASTC_6x6_Format, RGBA_ASTC_8x5_Format, RGBA_ASTC_8x6_Format, RGBA_ASTC_8x8_Format, RGBA_BPTC_Format, RGBA_ETC2_EAC_Format, RGBA_PVRTC_2BPPV1_Format, RGBA_PVRTC_4BPPV1_Format, RGBA_S3TC_DXT1_Format, RGBA_S3TC_DXT3_Format, RGBA_S3TC_DXT5_Format, RGBFormat, RGBIntegerFormat, RGB_BPTC_SIGNED_Format, RGB_BPTC_UNSIGNED_Format, RGB_ETC1_Format, RGB_ETC2_Format, RGB_PVRTC_2BPPV1_Format, RGB_PVRTC_4BPPV1_Format, RGB_S3TC_DXT1_Format, RGFormat, RGIntegerFormat, Rec709Primaries, RedFormat, RedIntegerFormat, ReinhardToneMapping, RepeatWrapping, ReplaceStencilOp, ReverseSubtractEquation, SIGNED_RED_GREEN_RGTC2_Format, SIGNED_RED_RGTC1_Format, SRGBColorSpace, SRGBTransfer, ShortType, SrcAlphaFactor, SrcAlphaSaturateFactor, SrcColorFactor, StaticCopyUsage, StaticDrawUsage, StaticReadUsage, StreamCopyUsage, StreamDrawUsage, StreamReadUsage, SubtractEquation, SubtractiveBlending, TOUCH, TangentSpaceNormalMap, TriangleFanDrawMode, TriangleStripDrawMode, TrianglesDrawMode, UVMapping, UnsignedByteType, UnsignedInt248Type, UnsignedInt5999Type, UnsignedIntType, UnsignedShort4444Type, UnsignedShort5551Type, UnsignedShortType, VSMShadowMap, WebGLCoordinateSystem, WebGPUCoordinateSystem, WrapAroundEnding, ZeroCurvatureEnding, ZeroFactor, ZeroSlopeEnding, ZeroStencilOp } from './constants.js';
export { WebGLMultipleRenderTargets } from './Three.Legacy.js';
import './renderers/webgl/WebGLAnimation.js';
import './renderers/webgl/WebGLAttributes.js';
import './renderers/webgl/WebGLBackground.js';
import './renderers/webgl/WebGLBindingStates.js';
import './renderers/webgl/WebGLBufferRenderer.js';
import './renderers/webgl/WebGLCapabilities.js';
import './renderers/webgl/WebGLClipping.js';
import './renderers/webgl/WebGLCubeMaps.js';
import './renderers/webgl/WebGLCubeUVMaps.js';
import './renderers/webgl/WebGLExtensions.js';
import './renderers/webgl/WebGLGeometries.js';
import './renderers/webgl/WebGLIndexedBufferRenderer.js';
import './renderers/webgl/WebGLInfo.js';
import './renderers/webgl/WebGLMorphtargets.js';
import './renderers/webgl/WebGLObjects.js';
import './renderers/webgl/WebGLPrograms.js';
import './renderers/webgl/WebGLProgram.js';
import './renderers/webgl/WebGLUniforms.js';
import './renderers/webgl/WebGLShader.js';
import './renderers/webgl/WebGLShaderCache.js';
import './renderers/webgl/WebGLProperties.js';
import './renderers/webgl/WebGLRenderLists.js';
import './renderers/webgl/WebGLRenderStates.js';
import './renderers/webgl/WebGLLights.js';
import './renderers/webgl/WebGLShadowMap.js';
import './renderers/shaders/ShaderLib/vsm.glsl.js';
import './renderers/webgl/WebGLState.js';
import './renderers/webgl/WebGLTextures.js';
import './renderers/webxr/WebXRManager.js';
import './renderers/webxr/WebXRController.js';
import './renderers/webxr/WebXRDepthSensing.js';
import './renderers/webgl/WebGLMaterials.js';
import './renderers/webgl/WebGLUniformsGroups.js';
import './renderers/shaders/ShaderChunk/alphahash_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/alphahash_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/alphamap_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/alphamap_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/alphatest_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/alphatest_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/aomap_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/aomap_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/batching_pars_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/batching_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/begin_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/beginnormal_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/bsdfs.glsl.js';
import './renderers/shaders/ShaderChunk/iridescence_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/bumpmap_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/clipping_planes_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/clipping_planes_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/clipping_planes_pars_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/clipping_planes_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/color_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/color_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/color_pars_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/color_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/common.glsl.js';
import './renderers/shaders/ShaderChunk/cube_uv_reflection_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/defaultnormal_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/displacementmap_pars_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/displacementmap_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/emissivemap_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/emissivemap_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/colorspace_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/colorspace_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/envmap_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/envmap_common_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/envmap_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/envmap_pars_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/envmap_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/fog_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/fog_pars_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/fog_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/fog_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/gradientmap_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/lightmap_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/lights_lambert_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/lights_lambert_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/lights_pars_begin.glsl.js';
import './renderers/shaders/ShaderChunk/envmap_physical_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/lights_toon_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/lights_toon_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/lights_phong_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/lights_phong_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/lights_physical_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/lights_physical_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/lights_fragment_begin.glsl.js';
import './renderers/shaders/ShaderChunk/lights_fragment_maps.glsl.js';
import './renderers/shaders/ShaderChunk/lights_fragment_end.glsl.js';
import './renderers/shaders/ShaderChunk/logdepthbuf_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/logdepthbuf_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/logdepthbuf_pars_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/logdepthbuf_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/map_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/map_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/map_particle_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/map_particle_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/metalnessmap_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/metalnessmap_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/morphinstance_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/morphcolor_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/morphnormal_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/morphtarget_pars_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/morphtarget_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/normal_fragment_begin.glsl.js';
import './renderers/shaders/ShaderChunk/normal_fragment_maps.glsl.js';
import './renderers/shaders/ShaderChunk/normal_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/normal_pars_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/normal_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/normalmap_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/clearcoat_normal_fragment_begin.glsl.js';
import './renderers/shaders/ShaderChunk/clearcoat_normal_fragment_maps.glsl.js';
import './renderers/shaders/ShaderChunk/clearcoat_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/iridescence_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/opaque_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/packing.glsl.js';
import './renderers/shaders/ShaderChunk/premultiplied_alpha_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/project_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/dithering_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/dithering_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/roughnessmap_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/roughnessmap_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/shadowmap_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/shadowmap_pars_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/shadowmap_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/shadowmask_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/skinbase_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/skinning_pars_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/skinning_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/skinnormal_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/specularmap_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/specularmap_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/tonemapping_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/tonemapping_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/transmission_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/transmission_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/uv_pars_fragment.glsl.js';
import './renderers/shaders/ShaderChunk/uv_pars_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/uv_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/worldpos_vertex.glsl.js';
import './renderers/shaders/ShaderLib/background.glsl.js';
import './renderers/shaders/ShaderLib/backgroundCube.glsl.js';
import './renderers/shaders/ShaderLib/cube.glsl.js';
import './renderers/shaders/ShaderLib/depth.glsl.js';
import './renderers/shaders/ShaderLib/distanceRGBA.glsl.js';
import './renderers/shaders/ShaderLib/equirect.glsl.js';
import './renderers/shaders/ShaderLib/linedashed.glsl.js';
import './renderers/shaders/ShaderLib/meshbasic.glsl.js';
import './renderers/shaders/ShaderLib/meshlambert.glsl.js';
import './renderers/shaders/ShaderLib/meshmatcap.glsl.js';
import './renderers/shaders/ShaderLib/meshnormal.glsl.js';
import './renderers/shaders/ShaderLib/meshphong.glsl.js';
import './renderers/shaders/ShaderLib/meshphysical.glsl.js';
import './renderers/shaders/ShaderLib/meshtoon.glsl.js';
import './renderers/shaders/ShaderLib/points.glsl.js';
import './renderers/shaders/ShaderLib/shadow.glsl.js';
import './renderers/shaders/ShaderLib/sprite.glsl.js';
import './lights/SpotLightShadow.js';
import './lights/LightShadow.js';
import './lights/PointLightShadow.js';
import './lights/DirectionalLightShadow.js';
import '../../_chunks/Curves-cjyKFada.js';
import './extras/Earcut.js';
import './renderers/shaders/ShaderChunk/default_vertex.glsl.js';
import './renderers/shaders/ShaderChunk/default_fragment.glsl.js';
import './extras/core/Interpolations.js';
